### ISSUE TITLE
[feature request] Better format for large transactions

### ISSUE THREAD

**Issue by matiya** [cantino/reckon#108]
Thank you for this package, I can't believe I was doing this stuff by hand for almost a year when this was available.

Now, I live in Chile and here the transactions can easily run into the millions. Usually I use a comma to separate millions from thousands, for instance:

```
2021-01-13	SOME TRANSACTION
	Expenses:SomeAccount    CLP 1,234,567.00			
	Assets:Bank			
```
With reckon I get:

```
2021-01-13	SOME TRANSACTION
	Expenses:SomeAccount    CLP 1234567.00			
	Assets:Bank			
```
Which is a little hard to read. 

Do you think you could add support for placing comma separators in large transactions?

**Comment by benprew** [comment]
Hi @matiya, thanks for using Reckon, I'm glad you like it.  Yeah, I think adding thousands separators makes sense, I've got a branch that I'm working on for this.  I'll let you know when I have something for you to test.

**Comment by benprew** [comment]
@matiya I pushed reckon 0.7.2 that should add commas on output by default.  Let me know how it works.

Thanks

**Comment by matiya** [comment]
It works!
I ran the same command in version 0.7.1 and 0.7.2 and I get the following diff:

```
> 2021-04-17    
83c99
<       Pasivos:Cuenta                 CLP 1014294.00
---
>       Pasivos:Cuenta                 -CLP 1,014,294.00

```

Thank you! This is a big improvement for my use case

**Comment by benprew** [comment]
Great!  Glad it's working and thanks for helping make reckon better.
