### ISSUE TITLE
Reckon behaviour does not match what is explained on README.md

### ISSUE THREAD

**Issue by SiliconKite** [cantino/reckon#112]
From the example on the README, I should be able of running reckon like so:

```
reckon --encoding 'UTF-8' -c 'EUR' \
--contains-header 1 \
--unattended \
--account-tokens tokens.yaml \
-f mymovements.csv \
-o ledger.dat
```

However, I get the following error:

ERROR: Must specify --account in unattended mode

**Comment by benprew** [comment]
Ahh, good catch, I'll update the README to clarify that --account is needed.

Thanks for using Reckon!
