### ISSUE TITLE
--date-format '%d/%m/%Y' not working

### ISSUE THREAD

**Issue by DurhamSmith** [cantino/reckon#113]
I am trying to parse data thats date is d/m/Y, e.g:
`1,12345,08/09/2014,08/09/2014,"SMS Notification Fee","","Fees","Fees",0.80,,-0.80`

When I try run reckon on this the date format (in the csv) is taken to be m/d/Y, and does not parse the input correctly, it confuses day and month. If I try add the --date-format '%d/%m/%Y' option I get:

I'm having trouble parsing Posting Date with the desired format: %d/%m/%Y

**Comment by benprew** [comment]
I think what's happening is that reckon is trying to parse the header value ("Posting Date") as a date.  You should be able to use the contains-header option to ignore the first line:

```
--contains-header 1
```

Give that a try and let me know if that fixes it.

Thanks!

**Comment by DurhamSmith** [comment]
Thanks that works for me!
