### ISSUE TITLE
Beancount support

### ISSUE THREAD

**Issue by dgmdevelopment** [cantino/reckon#119]
Hi, this is a very helpful tool! Just one request - add support for beancount transactions.  Thanks for considering!

**Comment by benprew** [comment]
Hi @dgmdevelopment thanks for your interest in reckon.  Do you happen to have a reference for the beancount transaction format I could look at?  I don't know how it compares to the ledger format.

Thanks

**Comment by larryopoly** [comment]
This looks like an awesome tool. I'd love to try it out with my beancount file. Hi @benprew, if you're still interested in having a look at beancount transactions, here's a few lines:
```
2015-12-29 * "Kin Soy" "Eating out with Joe"
  Liabilities:US:Chase:Slate                       -39.79 USD
  Expenses:Food:Restaurant                          39.79 USD

2015-12-30 balance Liabilities:US:Chase:Slate     -978.70 USD

2016-01-03 * "Chichipotle" "Eating out with Julie"
  Liabilities:US:Chase:Slate                       -58.01 USD
  Expenses:Food:Restaurant                          58.01 USD
```

See here for a full example beancount file: https://fava.pythonanywhere.com/example-beancount-file/editor/

**Comment by benprew** [comment]
Hi @larryopoly, sorry for the delayed response. Thanks for the sample file, that will be useful to test against, though it doesn't tell me much about how the syntax should be parsed.

I did, however, find this doc:

https://docs.google.com/document/d/1wAMVrKIA2qtRGmoVDSUBJGmYZSygUaR0uOMW1GV3YE0/edit#

And a script for converting ledger to beancount format (of course it's in perl):

https://github.com/beancount/ledger2beancount/blob/master/bin/ledger2beancount

I'll see if I can take a look at this some more this weekend and I'll let you know when I have something to test against.

Thanks!

**Comment by benprew** [comment]
@larryopoly I have a beta release up for beancount support, can you download it and give it a try?

https://github.com/cantino/reckon/releases/tag/v0.9.0-beta

Thanks!

**Comment by benprew** [comment]
Added support for beancount in 7119459237bebaf9f7bbd2f23a5675924509dcf3 and v0.9.1

**Comment by sagarbehere** [comment]
Is Beancount support still available? I don’t see Beancount mentioned anywhere in the main documentation, not even the —ledger-format (?) option.

**Comment by benprew** [comment]
Yes Beancount is supported! 

You can specify `--ledger-format BEANCOUNT` to use it. 

I'll update the github README to show the flag.

**Comment by sagarbehere** [comment]
Good to hear. This was actually one of the factors for me to decide between Beancount and hledger. Thank you so much 🙏
