### ISSUE TITLE
More than one column support

### ISSUE THREAD

**Issue by TheLugal** [cantino/reckon#120]
Hello! Reckon is a great project, thank you :) 

One of my banks operates with two money columns as in the following example
```csv
Date;Description;Rate date;In;Out;To account;From account;
"17.01.2022";"MORTGAGE BANK Inc.";;;"-2285,00";"12687686854";"45665485236";
"10.01.2022";"Salary";;"10550,00";;"45665485236";"16467168111";
```

For readability
```
┌────────────┬────────────────────┬─────────┬──────────┬──────────┬─────────────┬─────────────┐
│        Date│         Description│Rate date│        In│       Out│   To account│ From account│
├────────────┼────────────────────┼─────────┼──────────┼──────────┼─────────────┼─────────────┤
│"17.01.2022"│"MORTGAGE BANK Inc."│         │          │"-2285,00"│"12687686854"│"45665485236"│
│"10.01.2022"│            "Salary"│         │"10550,00"│          │"45665485236"│"16467168111"│
└────────────┴────────────────────┴─────────┴──────────┴──────────┴─────────────┴─────────────┘
```

Personally I don't entirely get why, but I have to deal with it regardless. I would very much like support for two money columns. I believe I could fix it using some `awk` magic or some such, but I expect I'm not the only one with this issue. Particularly since I see PR #118 mentions it.

Thank you for your consideration, and have an excellent day.

**Comment by wakatara** [comment]
I have this issue as well with one of my banks. I've been dealing with it by pre-processing the file in a spreadsheet and an `=IF(C2, C2, -1*D2)` type formula to merge the withdrawals and deposits. But yeah, now you mention it, two column support would be amazing.

**Comment by benprew** [comment]
Thanks for filing an issue @TheLugal. I haven't been following this project much lately, but I'll take a look at #118 and see if it can be merged.

Also, reckon tries to identify when a file has 2 money columns like this. Can either of you (@TheLugal or @wakatara) provide a larger sample? I'd like to see what is preventing reckon from identifying this correctly.

While it would be nice to have reckon always automatically identify 2 money columns, having an explicit argument is a good fallback when it doesn't.

Thanks!

**Comment by benprew** [comment]
reckon 0.9.0 with multiple money columns support was just released. You should be able to get it from rubygems or you can download the gem directly from the releases page on github.
