### ISSUE TITLE
Date formats

### ISSUE THREAD

**Issue by sprock** [cantino/reckon#126]
Hello,

I have entries like this in a CSV file:

date,description,debit,credit
2023-11-20,Point of Sale - Interac RETAIL PURCHASE 000001553028 CIRCLE K # 252,100.54,

When I invoke reckon:

reckon --contains-header -f my.csv -p

I get:

.rvm/gems/ruby-3.1.2/gems/reckon-0.9.3/lib/reckon/date_column.rb:85:in `parse': integer 303909302970 too big to convert to `int' (RangeError)
.rvm/gems/ruby-3.1.2/gems/reckon-0.9.3/lib/reckon/date_column.rb:85:in `likelihood'

from which I infer that reckon does not recognise the date format.  I tried:

reckon --contains-header --date-format '%Y-%m-%d' -f my.csv -p

but the problem resists.

Thanks for any help.

**Comment by benprew** [comment]
Hi @sprock , thanks for reaching out about this bug report. I'll get it fixed, but in the meantime, you should be able to avoid the error by setting the date-column explicitly:

```
reckon --contains-header -f my.csv -p --date-column 1
```

Give that a try and let me know if you're still having an issue.

Thanks!

**Comment by benprew** [comment]
Fixed in reckon 0.9.4.
