### ISSUE TITLE
Reckon fails immediately with error about uninitialized constant `Readline`

### ISSUE THREAD

**Issue by lukeadamson** [cantino/reckon#129]
I've installed reckon per the README, but when I try using it, I get the error below. @benprew Any suggestions? I'm using Ruby 3.2.2, installed via "brew install ruby" on macOS 14.1.1.

# reckon -f current.csv -o current.dat
/Users/luke/.local/share/gem/ruby/3.2.0/gems/highline-3.0.0/lib/highline/terminal.rb:127:in `block in readline_read': uninitialized constant HighLine::Terminal::Readline (NameError)

        Readline.readline(prompt, true)
        ^^^^^^^^
Did you mean?  Reline
	from /Users/luke/.local/share/gem/ruby/3.2.0/gems/highline-3.0.0/lib/highline/terminal.rb:173:in `run_preserving_stty'
	from /Users/luke/.local/share/gem/ruby/3.2.0/gems/highline-3.0.0/lib/highline/terminal.rb:125:in `readline_read'
	from /Users/luke/.local/share/gem/ruby/3.2.0/gems/highline-3.0.0/lib/highline/terminal.rb:100:in `get_line_with_readline'
	from /Users/luke/.local/share/gem/ruby/3.2.0/gems/highline-3.0.0/lib/highline/terminal.rb:87:in `get_line'
	from /Users/luke/.local/share/gem/ruby/3.2.0/gems/highline-3.0.0/lib/highline.rb:542:in `get_line'
	from /Users/luke/.local/share/gem/ruby/3.2.0/gems/highline-3.0.0/lib/highline.rb:526:in `get_response_line_mode'
	from /Users/luke/.local/share/gem/ruby/3.2.0/gems/highline-3.0.0/lib/highline/question.rb:534:in `get_response'
	from /Users/luke/.local/share/gem/ruby/3.2.0/gems/highline-3.0.0/lib/highline/question.rb:546:in `get_response_or_default'
	from /Users/luke/.local/share/gem/ruby/3.2.0/gems/highline-3.0.0/lib/highline/question_asker.rb:31:in `ask_once'
	from /Users/luke/.local/share/gem/ruby/3.2.0/gems/highline-3.0.0/lib/highline.rb:223:in `ask'
	from /Users/luke/.local/share/gem/ruby/3.2.0/gems/reckon-0.9.4/lib/reckon/options.rb:176:in `parse_command_line_options'
	from /Users/luke/.local/share/gem/ruby/3.2.0/gems/reckon-0.9.4/bin/reckon:7:in `<top (required)>'
	from /Users/luke/.local/share/gem/ruby/3.2.0/bin/reckon:25:in `load'
	from /Users/luke/.local/share/gem/ruby/3.2.0/bin/reckon:25:in `<main>'

**Comment by benprew** [comment]
Hi Luke, it looks like you're running reckon 0.9.4, if you install 0.9.5
(just released) it should fix it.

Thanks and let me know if that works.

**Comment by benprew** [comment]
Closing stale ticket.
