### ISSUE TITLE
Is it possible to use reckon with only no info about incoming or going out?

### ISSUE THREAD

**Issue by jodusan** [cantino/reckon#131]
My bank's csv file doesnt have +- or any other way of knowing if money went in or out (its all positive values). Is it possible to specify it somehow when prompted for account upon csv parsing?

**Comment by benprew** [comment]
Hi Dusan,

That's interesting, are the credits and debits separate columns or a single
column? If there a balance column that you can use to identify a credit vs
a debit?

Can you send me some example lines?

Thanks for using reckon!

**Comment by jodusan** [comment]
Here it is:﻿
﻿
﻿CreditorName,CreditorAccountNumber,CurrencyAmount,CurrencyCode,PurposeDescription,PurposeCode,ValueDate
,,1200.00,RSD,"Company1",,6.6.2023
,,3700.00,RSD,"Beer Bar",,6.6.2023
,,18996.96,RSD,"Inkbox Tatoos",,6.6.2023
,,1205.90,RSD,"Doordash",,6.6.2023
,,965.00,RSD,"Restaurant",,6.6.2023
,,5366.00,RSD,"Pharmacy",,6.6.2023
,,6000.00,RSD,"ATM cash withdrawal",,29.5.2023
John Smith,123456789101242142,10000.00,RSD,"Johnatella Smith payed me",289,5.6.2023  #incoming
John Smith,115000000007435793,40000.61,RSD,"Salary from company",240,2.6.2023 #incoming
,,1.00,EUR,"Supermarket, BARCELONA",,11.4.2023 # different currency
MobilePhoneCompany,4219002141024,2644.43,RSD,MobilePhoneCompany-User24102,289,25.5.2023
ParkingService,100299129999211,935.00,RSD,Parkingticket 22921,289,21.5.2023

**Comment by jodusan** [comment]
Here it is, in addition to not having +- also there are two currencies, is this supported? Thanks!
﻿
﻿CreditorName,CreditorAccountNumber,CurrencyAmount,CurrencyCode,PurposeDescription,PurposeCode,ValueDate
,,1200.00,RSD,"Company1",,6.6.2023
,,3700.00,RSD,"Beer Bar",,6.6.2023
,,18996.96,RSD,"Inkbox Tatoos",,6.6.2023
,,1205.90,RSD,"Doordash",,6.6.2023
,,965.00,RSD,"Restaurant",,6.6.2023
,,5366.00,RSD,"Pharmacy",,6.6.2023
,,6000.00,RSD,"ATM cash withdrawal",,29.5.2023
John Smith,123456789101242142,10000.00,RSD,"Johnatella Smith payed me",289,5.6.2023  #incoming
John Smith,123456789101242142,40000.61,RSD,"Salary from company",240,2.6.2023 #incoming
,,1.00,EUR,"Supermarket, BARCELONA",,11.4.2023 # different currency
MobilePhoneCompany,4219002141024,2644.43,RSD,MobilePhoneCompany-User24102,289,25.5.2023
ParkingService,100299129999211,935.00,RSD,Parkingticket 22921,289,21.5.2023

**Comment by benprew** [comment]
Wow, that's wild, so there's no way to determine just by looking at the lines if it's a credit or debit?

If that's true, there's not much reckon can do. I'd recommend preprocessing the file to add +/- where necessary. 

Reckon doesn't support modifying a line manually, and I would think it would be faster to modify the file all at once, instead of having to edit each line.

What were you thinking the workflow would look like?

**Comment by jodusan** [comment]
@benprew I can preprocess the +- so thats fine. But what about two currencies?

**Comment by jodusan** [comment]
i can split also in two thanks
