### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by yga01** [cantino/reckon#133]
Hello Ben,

I don't know if this is the correct way to contact you, if it is not then sorry.

I am using reckon actively, my ledger file has about 30.000 transaction and 10 years history. Processing my bank statements with reckon works very nicely. I have a small feature request though. Reckon sorts transactions on date. That seems logical, but it means I have to look at each transaction very carefully and decide about the second account name. For me it would work much quicker if reckon sorts on a payee's account number or name or even a description. I would then see all similar transaction in one batch and it would speed up my processing.

I tried to do this myself, I downloaded the repository and changed line 171 in app.rb, but I failed to get it working, I don't know ruby and I don't know git so that was a fail. If you could do it that would be great, if not I will keep using it anyways, I like it.

Thank you,
Ysbrand Galama.

**Comment by benprew** [comment]
Hi Ysbrand, thanks for filing an issue.

I also often find myself wanting to sort transactions on something other than date. I will take a look and see if I can implement this feature, but line 171 was the right line to make that change. 

If you had the reckon gem installed, it was likely using those libs and not the version you had changed.

An easy way to make it use the version you had downloaded is to set the $RUBYLIB variable to the lib/ directory of reckon.

ex.

    export RUBYLIB=$HOME/src/reckon/lib

**Comment by benprew** [comment]
@yga01 Sorting support released in reckon 0.10.0. Try it out and let me know what you think.

Thanks!

**Comment by yga01** [comment]
Yep, works perfect.
Thanks a lot Ben!
