### ISSUE TITLE
Debit/Credit Columns from SunTrust

### ISSUE THREAD

**Issue by DonnieP** [cantino/reckon#42]
This is from SunTrust.  It has separate Debit and Credit columns which are not signed.  Reckon will pick up either the Debit or Credit column, but I can't get it to recognize that Debit is checks and Credit is deposits.

Date,Check Number,Description,Debit,Credit,Running Balance
11/03/2014,0, AMEX EPayment    ACH PMT    A26,100.00,0,500.00
11/07/2014,0, AcadiaHealthcare PAYROLL  ,0,100.00,600.00

reckon -f mwe.csv -v -p --contains-header --date-format '%d/%m/%Y' --ignore-columns 2,6

I didn't find a high-likelyhood money column, but I'm taking my best guess with column 4.
+------------+----------+-----------------------------------+
| Date       | Amount   | Description                       |
+------------+----------+-----------------------------------+
| 2014/03/11 |  $0.00   | AMEX EPayment ACH PMT A26; 100.00 |
| 2014/07/11 |  $100.00 | AcadiaHealthcare PAYROLL; 0       |
+------------+----------+-----------------------------------+

**Comment by BlackEdder** [comment]
I thought this should work. How large is the csv file though, if it is only two rows then reckon does not have enough data to figure it out.

Could you attach an example csv file?

**Comment by DonnieP** [comment]
Actual file is 38 rows.  SunTrust won't download more than 90 days at a time.

**Comment by BlackEdder** [comment]
That should be plenty. Could you attach/copy and paste the (anonimized) csv file?

**Comment by DonnieP** [comment]
Date: Mon, 9 Feb 2015 04:30:11 -0800

**Comment by cantino** [comment]
Great!  Pushing an update to the gem now.
