### ISSUE TITLE
Problem with mint file

### ISSUE THREAD

**Issue by boydkelly** [cantino/reckon#53]
Hi,

Has been a while since I've used this but getting error when processing a csv file.  When I run with the -p option all seems ok; I get the table output.  However removing the -p and using -o output.dat or anytthing else produces the following error:

 reckon --contains-header -f input.csv -a Mastercard --ignore-columns 2,5,6,7,8,9.10 
I didn't find a high-likelyhood money column, but I'm taking my best guess with column 3.
+------------+--------+----------------------------------+
| 2015/09/23 |  $4.43 | STARBUCKS B12 20251500 CHICAGO I |
+------------+--------+----------------------------------+
/usr/local/share/gems/gems/reckon-0.4.3/lib/reckon/app.rb:102:in `block (2 levels) in walk_backwards': undefined method`completion=' for #HighLine::Question:0x0055cbe5808700 (NoMethodError)
    from /usr/local/share/gems/gems/highline-1.6.15/lib/highline/question.rb:58:in `initialize'
    from /usr/local/share/gems/gems/highline-1.6.15/lib/highline.rb:237:in`new'
    from /usr/local/share/gems/gems/highline-1.6.15/lib/highline.rb:237:in `ask'
    from /usr/local/share/gems/gems/reckon-0.4.3/lib/reckon/app.rb:101:in`block in walk_backwards'
    from /usr/local/share/gems/gems/reckon-0.4.3/lib/reckon/app.rb:219:in `block in each_row_backwards'
    from /usr/local/share/gems/gems/reckon-0.4.3/lib/reckon/app.rb:218:in`each'
    from /usr/local/share/gems/gems/reckon-0.4.3/lib/reckon/app.rb:218:in `each_row_backwards'
    from /usr/local/share/gems/gems/reckon-0.4.3/lib/reckon/app.rb:82:in`walk_backwards'
    from /usr/local/share/gems/gems/reckon-0.4.3/bin/reckon:19:in `<top (required)>'
    from /usr/local/bin/reckon:23:in`load'
    from /usr/local/bin/reckon:23:in `<main>'

cat input.csv 
Date,Description,Original Description,Amount,Transaction Type,Category,Account Name,Labels,Notes
9/23/2015,Starbucks,STARBUCKS B12 20251500 CHICAGO I,4.43,debit,Coffee Shops,MasterCard,,
9/23/2015,Starbucks,STARBUCKS B12 20251500 CHICAGO I,1.18,debit,Coffee Shops,MasterCard,,

with -p:

reckon --contains-header -f input.csv -a Mastercard --ignore-columns 2,5,6,7,8,9.10 -p
I didn't find a high-likelyhood money column, but I'm taking my best guess with column 3.
+------------+--------+----------------------------------+
| Date       | Amount | Description                      |
+------------+--------+----------------------------------+
| 2015/09/23 |  $4.43 | STARBUCKS B12 20251500 CHICAGO I |
| 2015/09/23 |  $1.18 | STARBUCKS B12 20251500 CHICAGO I |
+------------+--------+----------------------------------+

Python 2.7.10 on Fedora 23

**Comment by BlackEdder** [comment]
The crash is because it can't find the completion method, which should be part of the highline gem. Which version of highline do you have installed?
```
gem list --local | grep highline
```

**Comment by benprew** [comment]
Closing this issue, let me know if it's still an issue and we can reopen it.
