### ISSUE TITLE
Parsing account names does not work if currency symbol is different from $

### ISSUE THREAD

**Issue by paulkoerbitz** [cantino/reckon#56]
At lib/reckon/ledger_parser.rb:27 the regex checking for an account name explicitly checks for a $ sign. This doesn't work if one uses a currency symbol other than $.

**Comment by cantino** [comment]
Hey @paulkoerbitz, thanks for letting us know!  Would you be interested in submitting a PR to fix this?

**Comment by thedd** [comment]
I tried to fix this issue. 
See #61.

**Comment by TomK32** [comment]
This wouldn't cover the use of multiple currency in a single file.

I searched for regexp on other parser implementation and this one is python looks very promising: https://github.com/Tagirijus/ledger-parse/blob/master/ledgerparse.py

**Comment by omangin** [comment]
I just posted some quick and dirty solution to support multi-currency as #76 in case anyone is interested.
