### ISSUE TITLE
Error in reckon for the same format csv file

### ISSUE THREAD

**Issue by vikrantrathore** [cantino/reckon#57]
Reckon works with the files downloaded in previous months but then fails on the newly downloaded csv file from bank. The format pf the file is precisely same with 2 money columns. The error is cryptic and undecipherabl. I can't get an idea which line in csv is creating this issue. I checked the code and didn't find any clues either.

/usr/local/lib/ruby/gems/2.3.0/gems/reckon-0.4.4/lib/reckon/csv_parser.rb:47:in `block in description_for': undefined method `empty?' for nil:NilClass (NoMethodError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/reckon-0.4.4/lib/reckon/csv_parser.rb:47:in `reject'
	from /usr/local/lib/ruby/gems/2.3.0/gems/reckon-0.4.4/lib/reckon/csv_parser.rb:47:in `description_for'
	from /usr/local/lib/ruby/gems/2.3.0/gems/reckon-0.4.4/lib/reckon/app.rb:241:in `block in each_row_backwards'
	from /usr/local/lib/ruby/gems/2.3.0/gems/reckon-0.4.4/lib/reckon/app.rb:235:in `each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/reckon-0.4.4/lib/reckon/app.rb:235:in `each_row_backwards'
	from /usr/local/lib/ruby/gems/2.3.0/gems/reckon-0.4.4/lib/reckon/app.rb:97:in `walk_backwards'
	from /usr/local/lib/ruby/gems/2.3.0/gems/reckon-0.4.4/bin/reckon:19:in `<top (required)>'
	from /usr/local/bin/reckon:23:in `load'
	from /usr/local/bin/reckon:23:in `<main>'

**Comment by cantino** [comment]
Hey @vikrantrathore, sorry to hear that.

Would you be able to email me (andrew at andrewcantino dot com) a copy of the CSV, or is it sensitive?

**Comment by vikrantrathore** [comment]
Cannot send you the copy as it is sensitive bank statement. Just to let you know that file contains Chinese Characters in csv file, not sure if thats the problem.

It works with newer files without Chinese characters. So probably you can look into it or just close the issue as it works wit other files not using CJK (Chinese, Japanese, Korean) unicode characters.

**Comment by vikrantrathore** [comment]
Do you still want to get a sample file with CJK?

**Comment by cantino** [comment]
Sure, that'd be helpful @vikrantrathore.

**Comment by seblemaguer** [comment]
Hello, 

I faced the same problem until I realized that the csv file was malformed. Be sure that your string fields are in quotes. For me it solved the problem

**Comment by vikrantrathore** [comment]
The issue is fixed, one of the description lines in csv file contained a , and it was not enclosed in quotes. thanks @seblemaguer and @cantino for reckon.
