### ISSUE TITLE
Reckon doesn't learn from multiple sources

### ISSUE THREAD

**Issue by manishrjain** [cantino/reckon#63]
I have a ledger file that I already use, and set the `-l` option for reckon to use. In addition, I also have a `tokens.yaml` file for the entries that reckon generally gets wrong. The expected behavior of reckon, ideally, would be that it checks against `tokens.yaml` file first. And if there's no match there, then against the `-l` option. But instead, reckon only checks one of those two.

Reckon doesn't understand the `include` directive of ledger; and also doesn't accept multiple ledger files for the `-l` option. Which is a bit annoying, because then I have to concatenate them myself before presenting to reckon. So, would be great if reckon can learn one of these two.

**Comment by cantino** [comment]
Hey @manishrjain. Those sound like great suggestions.  I'm open to pull requests if you would like to work on any of those changes.

**Comment by manishrjain** [comment]
Ended up writing https://github.com/manishrjain/into-ledger, which fixes all the issues I saw with reckon.

**Comment by cantino** [comment]
Awesome! That looks like a great tool. Did you use naive bayes for classification?

**Comment by manishrjain** [comment]
Uses TF-IDF classifier using this: https://github.com/jbrukh/bayesian

**Comment by cantino** [comment]
Nice!
