### ISSUE TITLE
Reckon undefined method to_h when trying to parse csv file 

### ISSUE THREAD

**Issue by munkee** [cantino/reckon#66]
Just installed on OS X 10.11.6

`reckon --contains-header --account 'Liabilities:Credit Card:Chase United' -f Downloads/Chase7633_Activity_20160919.CSV -p`

Gives Error:
I didn't find a high-likelyhood money column, but I'm taking my best guess with column 5.
/Library/Ruby/Gems/2.0.0/gems/terminal-table-1.7.2/lib/terminal-table/table.rb:248:in `block (2 levels) in recalc_column_widths': undefined method `to_h' for [[10, [1]], [0, [0]]]:Array (NoMethodError)
       	from /Library/Ruby/Gems/2.0.0/gems/terminal-table-1.7.2/lib/terminal-table/table.rb:225:in `each'
       	from /Library/Ruby/Gems/2.0.0/gems/terminal-table-1.7.2/lib/terminal-table/table.rb:225:in `block in recalc_column_widths'
       	from /Library/Ruby/Gems/2.0.0/gems/terminal-table-1.7.2/lib/terminal-table/table.rb:223:in `each'
       	from /Library/Ruby/Gems/2.0.0/gems/terminal-table-1.7.2/lib/terminal-table/table.rb:223:in `recalc_column_widths'
       	from /Library/Ruby/Gems/2.0.0/gems/terminal-table-1.7.2/lib/terminal-table/table.rb:339:in `column_widths'
       	from /Library/Ruby/Gems/2.0.0/gems/terminal-table-1.7.2/lib/terminal-table/table.rb:97:in `column_width'
       	from /Library/Ruby/Gems/2.0.0/gems/terminal-table-1.7.2/lib/terminal-table/separator.rb:7:in `block in render'
       	from /Library/Ruby/Gems/2.0.0/gems/terminal-table-1.7.2/lib/terminal-table/separator.rb:6:in `map'
       	from /Library/Ruby/Gems/2.0.0/gems/terminal-table-1.7.2/lib/terminal-table/separator.rb:6:in `render'
       	from /Library/Ruby/Gems/2.0.0/gems/terminal-table-1.7.2/lib/terminal-table/table.rb:142:in `block in render'
       	from /Library/Ruby/Gems/2.0.0/gems/terminal-table-1.7.2/lib/terminal-table/table.rb:142:in `map'
       	from /Library/Ruby/Gems/2.0.0/gems/terminal-table-1.7.2/lib/terminal-table/table.rb:142:in `render'
       	from /Library/Ruby/Gems/2.0.0/gems/reckon-0.4.4/lib/reckon/app.rb:24:in `puts'
       	from /Library/Ruby/Gems/2.0.0/gems/reckon-0.4.4/lib/reckon/app.rb:24:in `puts'
       	from /Library/Ruby/Gems/2.0.0/gems/reckon-0.4.4/lib/reckon/app.rb:24:in `interactive_output'
       	from /Library/Ruby/Gems/2.0.0/gems/reckon-0.4.4/lib/reckon/app.rb:230:in `output_table'
       	from /Library/Ruby/Gems/2.0.0/gems/reckon-0.4.4/bin/reckon:10:in `<top (required)>'
       	from /usr/local/bin/reckon:23:in `load'
       	from /usr/local/bin/reckon:23:in `<main>'

My csv looks like 
`Type,Trans Date,Post Date,Description,Amount,Category,Memo`
`Sale,09/16/2016,09/18/2016,QT 880        08008807,-42.12,,null`

**Comment by cantino** [comment]
Hey @munkee, could you try telling Reckon the index of the money column?

**Comment by munkee** [comment]
How do I go about that? `reckon -h` doesn't show anything promising and I'm browsing the code but I'm ruby incompetent.

**Comment by cantino** [comment]
It's a bit kludgy, but you can probably add `--ignore-columns 4,6,7`

**Comment by munkee** [comment]
Same issue:

reckon --ignore-columns 4,6,7 --contains-header --account 'Liabilities:Credit Card:Case United' -f Downloads/Chase7633_Activity_20160919.CSV -p
I didn't find a high-likelyhood money column, but I'm taking my best guess with column 4.
/Library/Ruby/Gems/2.0.0/gems/terminal-table-1.7.2/lib/terminal-table/table.rb:248:in `block (2 levels) in recalc_column_widths': undefined method `to_h' for [[10, [1]], [0, [0]]]:Array (NoMethodError)
       	from /Library/Ruby/Gems/2.0.0/gems/terminal-table-1.7.2/lib/terminal-table/table.rb:225:in `each'
       	from /Library/Ruby/Gems/2.0.0/gems/terminal-table-1.7.2/lib/terminal-table/table.rb:225:in `block in recalc_column_widths'
       	from /Library/Ruby/Gems/2.0.0/gems/terminal-table-1.7.2/lib/terminal-table/table.rb:223:in `each'
       	from /Library/Ruby/Gems/2.0.0/gems/terminal-table-1.7.2/lib/terminal-table/table.rb:223:in `recalc_column_widths'
       	from /Library/Ruby/Gems/2.0.0/gems/terminal-table-1.7.2/lib/terminal-table/table.rb:339:in `column_widths'
       	from /Library/Ruby/Gems/2.0.0/gems/terminal-table-1.7.2/lib/terminal-table/table.rb:97:in `column_width'
       	from /Library/Ruby/Gems/2.0.0/gems/terminal-table-1.7.2/lib/terminal-table/separator.rb:7:in `block in render'
       	from /Library/Ruby/Gems/2.0.0/gems/terminal-table-1.7.2/lib/terminal-table/separator.rb:6:in `map'
       	from /Library/Ruby/Gems/2.0.0/gems/terminal-table-1.7.2/lib/terminal-table/separator.rb:6:in `render'
       	from /Library/Ruby/Gems/2.0.0/gems/terminal-table-1.7.2/lib/terminal-table/table.rb:142:in `block in render'
       	from /Library/Ruby/Gems/2.0.0/gems/terminal-table-1.7.2/lib/terminal-table/table.rb:142:in `map'
       	from /Library/Ruby/Gems/2.0.0/gems/terminal-table-1.7.2/lib/terminal-table/table.rb:142:in `render'
       	from /Library/Ruby/Gems/2.0.0/gems/reckon-0.4.4/lib/reckon/app.rb:24:in `puts'
       	from /Library/Ruby/Gems/2.0.0/gems/reckon-0.4.4/lib/reckon/app.rb:24:in `puts'
       	from /Library/Ruby/Gems/2.0.0/gems/reckon-0.4.4/lib/reckon/app.rb:24:in `interactive_output'
       	from /Library/Ruby/Gems/2.0.0/gems/reckon-0.4.4/lib/reckon/app.rb:230:in `output_table'
       	from /Library/Ruby/Gems/2.0.0/gems/reckon-0.4.4/bin/reckon:10:in `<top (required)>'
       	from /usr/local/bin/reckon:23:in `load'
       	from /usr/local/bin/reckon:23:in `<main>'

**Comment by cantino** [comment]
Thanks for trying it.  Could you see if #67 and the new `--date-column` and `--money-column` options fix this?

**Comment by munkee** [comment]
Same error except it doesn't complain about uncertainty for the money column:

reckon --money-column 5 --date-column 2 --contains-header --account 'Liabilities:Credit Card:Case United' -f ~/Downloads/Chase7633_Activity_20160919.CSV -p
/Library/Ruby/Gems/2.0.0/gems/terminal-table-1.7.2/lib/terminal-table/table.rb:248:in `block (2 levels) in recalc_column_widths': undefined method `to_h' for [[10, [1]], [0, [0]]]:Array (NoMethodError)
       	from /Library/Ruby/Gems/2.0.0/gems/terminal-table-1.7.2/lib/terminal-table/table.rb:225:in `each'
       	from /Library/Ruby/Gems/2.0.0/gems/terminal-table-1.7.2/lib/terminal-table/table.rb:225:in `block in recalc_column_widths'
       	from /Library/Ruby/Gems/2.0.0/gems/terminal-table-1.7.2/lib/terminal-table/table.rb:223:in `each'
       	from /Library/Ruby/Gems/2.0.0/gems/terminal-table-1.7.2/lib/terminal-table/table.rb:223:in `recalc_column_widths'
       	from /Library/Ruby/Gems/2.0.0/gems/terminal-table-1.7.2/lib/terminal-table/table.rb:339:in `column_widths'
       	from /Library/Ruby/Gems/2.0.0/gems/terminal-table-1.7.2/lib/terminal-table/table.rb:97:in `column_width'
       	from /Library/Ruby/Gems/2.0.0/gems/terminal-table-1.7.2/lib/terminal-table/separator.rb:7:in `block in render'
       	from /Library/Ruby/Gems/2.0.0/gems/terminal-table-1.7.2/lib/terminal-table/separator.rb:6:in `map'
       	from /Library/Ruby/Gems/2.0.0/gems/terminal-table-1.7.2/lib/terminal-table/separator.rb:6:in `render'
       	from /Library/Ruby/Gems/2.0.0/gems/terminal-table-1.7.2/lib/terminal-table/table.rb:142:in `block in render'
       	from /Library/Ruby/Gems/2.0.0/gems/terminal-table-1.7.2/lib/terminal-table/table.rb:142:in `map'
       	from /Library/Ruby/Gems/2.0.0/gems/terminal-table-1.7.2/lib/terminal-table/table.rb:142:in `render'
       	from /Library/Ruby/Gems/2.0.0/gems/reckon-0.4.4/lib/reckon/app.rb:24:in `puts'
       	from /Library/Ruby/Gems/2.0.0/gems/reckon-0.4.4/lib/reckon/app.rb:24:in `puts'
       	from /Library/Ruby/Gems/2.0.0/gems/reckon-0.4.4/lib/reckon/app.rb:24:in `interactive_output'
       	from /Library/Ruby/Gems/2.0.0/gems/reckon-0.4.4/lib/reckon/app.rb:230:in `output_table'
       	from /Library/Ruby/Gems/2.0.0/gems/reckon-0.4.4/bin/reckon:10:in `<top (required)>'
       	from /usr/local/bin/reckon:23:in `load'
       	from /usr/local/bin/reckon:23:in `<main>'

Do you know if anyone is successfully running this on OS X?

**Comment by munkee** [comment]
Installed ruby from Homebrew `ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]` instead of the 2.0.0 version that comes with OS X 10.11, reinstalled rake, rspec and bundler, reinstalled the reckon from pr/67 and it works. It also works with the version from master with a newer ruby. Sorry for leading us down this rabbit hole.

**Comment by cantino** [comment]
No worries, glad it's working.
