### ISSUE TITLE
Looking for a new maintainer for Reckon

### ISSUE THREAD

**Issue by cantino** [cantino/reckon#68]
I'm no longer actively using or developing reckon and do not intend to maintain it. If someone would be interested in taking ownership of the project and maintaining it, I'd be happy to pass the torch.

**Comment by mondras** [comment]
Just curious - what are you using now?

**Comment by cantino** [comment]
I'm not really using anything since I'm no longer running a small business where itemized expenses need to be tracked.

**Comment by benprew** [comment]
It me!
