### ISSUE TITLE
Support ISO 8601 formatting of dates in ledger file

### ISSUE THREAD

**Issue by adius** [cantino/reckon#70]
`2017-03-23` This should actually be the default In my opinion.
Don't know who invented that stupid slash format,
could have just used the ISO format in the first place.

For the time being my workaround is to reformat the file with ledger:

```sh
ledger -f reckon-output.ledger --date-format '%Y-%m-%d' print  > fixed.ledger
```

**Comment by benprew** [comment]
Good idea @ad-si, I've opened #77 to fix this.

**Comment by benprew** [comment]
This has been merged to master and will go out in the next version of the gem.
