### ISSUE TITLE
[Bug]? Reckon fails to run on ruby 2.7.0 on Catalina 

### ISSUE THREAD

**Issue by wakatara** [cantino/reckon#83]
Hola there!

I read your super interesting article about Reckon and using it with ledger and was trying to have a go. I installed reckon as per `gem install --user reckon`.
OS: OSX 10.15.3
ruby: ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin19] (installed via homebrew
gem: version 3.1.2
shell: fish version 3.1.0

I am getting the following when I try to run the basic reckon command.

```
~ reckon --version
/usr/local/lib/ruby/gems/2.7.0/gems/reckon-0.5.0/lib/reckon.rb:13: warning: already initialized constant LOGGER
/usr/local/lib/ruby/gems/2.7.0/gems/reckon-0.5.0/lib/reckon.rb:13: warning: previous definition of LOGGER was here
**Traceback** (most recent call last):
        6: from /usr/local/lib/ruby/gems/2.7.0/bin/reckon:23:in `<main>'
        5: from /usr/local/lib/ruby/gems/2.7.0/bin/reckon:23:in `load'
        4: from /usr/local/lib/ruby/gems/2.7.0/gems/reckon-0.5.0/bin/reckon:4:in `<top (required)>'
        3: from /usr/local/Cellar/ruby/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        2: from /usr/local/Cellar/ruby/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        1: from /usr/local/lib/ruby/gems/2.7.0/gems/reckon-0.5.0/lib/reckon.rb:16:in `<top (required)>'
/usr/local/lib/ruby/gems/2.7.0/gems/reckon-0.5.0/lib/reckon.rb:16:in `require_relative': **cannot load such file -- /usr/local/lib/ruby/gems/2.7.0/gems/reckon-0.5.0/lib/reckon/version (LoadError)**
 ~ echo $PATH
/bin /sbin /usr/local/bin /usr/local/sbin /Users/daryl/.cargo/bin /usr/local/opt/ruby/bin /Users/daryl/.gem/ruby/2.7.0/bin /usr/local/lib/ruby/gems/2.7.0/bin /usr/bin /usr/sbin /Users/daryl/.fzf/bin
~ which reckon
/usr/local/lib/ruby/gems/2.7.0/bin/reckon
```
(I also receive the same message if I install it via the `gem install --user reckon` option though of course the error message points to not being able to find `require_relative': cannot load such file -- /Users/daryl/.gem/ruby/2.7.0/gems/reckon-0.5.0/lib/reckon/version (LoadError)`

I have completely uninstalled reckon and then tried reinstalling it but still getting the same error. After poking around a little I am a little confused because other commands installed the same way seem to work fine. 

Any ideas as to what may be causing this? Bit stumped after checking paths etc at this point. Other gems I have seem to work fine   :-/.  

thanks!
Daryl.

**Comment by priteau** [comment]
This was fixed in master and the v.0.5.0 tag includes this commit, but it seems the gem itself is still buggy: https://github.com/cantino/reckon/commit/3274ae1c65f73dfbb0cd82644b43afef0d68c04e

@benprew Can you please make a bug fix release?

**Comment by wakatara** [comment]
Phew. I thought I was losing it and just got a new machine so worried I'd borked something terribly.  =p Thanks for letting me know.  =]

**Comment by wakatara** [comment]
(I am super excited to try this out btw... =] ).

**Comment by benprew** [comment]
Yikes, sorry about that, I thought I had uploaded the correct version of the gem.  I'll update the version 0.5.1 and get a fix out shortly.

Thanks!

**Comment by benprew** [comment]
Ok, I just updated reckon to 0.5.1, which should fix the issue.  If you're still having problems, let me know.

**Comment by benprew** [comment]
@wakatara  I'm going to close this issue, since it should be fixed now.  If it's not, please feel free to either reopen this issue or create a new one.  Thanks for using reckon :)
