### ISSUE TITLE
[FEATURE REQUEST] Ask for currency of Account and output in output file in standard format of xxxx TLA for currency

### ISSUE THREAD

**Issue by wakatara** [cantino/reckon#84]
A figure this is a very small hygiene fix, but it would save a lot of time for international people or people with multiple currencies (eg. everyone outside the United States =p) if when you asked for the initial account that reckon is dealing with you also asked for a default currency (I would highly recommend either $ (the default) for people in the US/Canada) and the three letter shortforms for most major currencies (eg. CAD, USD, GBP, SGD etc). 

Right now, I have to manually script changes to the file and convert every line with a $3500.00 etc to `3500.00 SGD` rather than the default $3500.00 (my ledger account has 5 different currencies it deals with plus equities and RSUs so being able to have it output would be a huge time saver.

Seriously great gem. This is making my life with ledger a magnitude better given the ledger-tools suite is a bit tetchy with date formats and the like. 

And thank you for spending the time to write this and blog on it! I would not hve run across this without the blog post. =]

**Comment by benprew** [comment]
I don't have much experience with non-US currencies, but reckon does have the --currency option, here's an example:

```
><> reckon -f ~/notes/finance/raw/Paypal-2019-07-02_2020-01-18.csv --currency 'SGD ' -o test.ledger
---------------------------------------------------+
| 2019-07-02 |  SGD 70.00 | Non-Confirmed; Credit |
+------------+------------+--------------------------------------------------------------------------------------------------------
Which account provided this income? ([account]/[q]uit/[s]kip) Income

><> cat test.ledger
2019-07-02      Non-Confirmed; Credit
Assets:Bank:Checking                                     SGD 70.00
Income                                   -SGD 70.00
```

Does that provide the functionality you're looking for?

Thanks

**Comment by wakatara** [comment]
Well, that's embarrassing that I didn't notice that. Sorry for not RTFM. 

It is basically the functionality yes, though would be curious if there is any way to get the TLA behind the amounts in the form like above but say,  `70.00 SGD`. since this is how it is generally represented accounting-wise in most ledgers.

thanks!
(btw, was super impressed with how this chewed through my accounts yesterday and spit out what I needed. Seriously, thanks for writing this.).

**Comment by benprew** [comment]
No problem, there's a lot of options to reckon.  Including one that will display the currency behind the amount.

```
        --suffixed
                                     If --currency should be used as a suffix. Defaults to false.
```

So the command before could be written like this:

`reckon -f ~/notes/finance/raw/Paypal-2019-07-02_2020-01-18.csv --currency 'SGD ' -o test.ledger --suffixed`

And it would produce a ledger file like this:

```
><> cat test.ledger
2019-07-02	Non-Confirmed; Credit
	Assets:Bank:Checking					 70.00 SGD
	Income					 -70.00 SGD
```
