### ISSUE TITLE
[BUG] Reckon appears not to be parsing ISO standard date yyyy-mm-dd?

### ISSUE THREAD

**Issue by wakatara** [cantino/reckon#85]
I just converted a file from one of my banks to have a yyyy-mm-dd date field via excel. I get the following error(s) when trying to run against it:

```shell
🚀 reckon --contains-header -f csv92468-endFeb-prepped.csv -l ~/Dropbox/Apps/ledger/2020.ledger -o ./reckon_RBC_Visa_test-endFeb.ledger
```
Dates are in the format 2020-02-20 (seriously... =]  Reconciling last month.)

Getting the following thrown error:

```shell
W, [2020-03-05T17:02:04.352498 #28186]  WARN -- : Skipping row: 'Visa, 4.51401E+15, 2020-02-20, , GOJEK SINGAPORE, 8.10 SGD @ .976500000000, -7.91, D' that doesn't have a valid date
W, [2020-03-05T17:02:04.357382 #28186]  WARN -- : Skipping row: 'Visa, 4.51401E+15, 2020-02-20, , GOJEK SINGAPORE, 6.00 SGD @ .976600000000, -5.86, D' that doesn't have a valid date
... 
Traceback (most recent call last):
        18: from /usr/local/lib/ruby/gems/2.7.0/bin/reckon:23:in `<main>'
        17: from /usr/local/lib/ruby/gems/2.7.0/bin/reckon:23:in `load'
        16: from /usr/local/lib/ruby/gems/2.7.0/gems/reckon-0.5.1/bin/reckon:19:in `<top (required)>'
        15: from /usr/local/lib/ruby/gems/2.7.0/gems/reckon-0.5.1/lib/reckon/app.rb:95:in `walk_backwards'
        14: from /usr/local/lib/ruby/gems/2.7.0/gems/reckon-0.5.1/lib/reckon/app.rb:158:in `each_row_backwards'
        13: from /usr/local/lib/ruby/gems/2.7.0/gems/reckon-0.5.1/lib/reckon/app.rb:158:in `each'
        12: from /usr/local/lib/ruby/gems/2.7.0/gems/reckon-0.5.1/lib/reckon/app.rb:159:in `block in each_row_backwards'
        11: from /usr/local/lib/ruby/gems/2.7.0/gems/reckon-0.5.1/lib/reckon/csv_parser.rb:45:in `date_for'
        10: from /usr/local/lib/ruby/gems/2.7.0/gems/reckon-0.5.1/lib/reckon/date_column.rb:43:in `for'
         9: from /usr/local/lib/ruby/gems/2.7.0/gems/chronic-0.10.2/lib/chronic.rb:90:in `parse'
         8: from /usr/local/lib/ruby/gems/2.7.0/gems/chronic-0.10.2/lib/chronic/parser.rb:61:in `parse'
         7: from /usr/local/lib/ruby/gems/2.7.0/gems/chronic-0.10.2/lib/chronic/parser.rb:244:in `tokens_to_span'
         6: from /usr/local/lib/ruby/gems/2.7.0/gems/chronic-0.10.2/lib/chronic/parser.rb:244:in `each'
         5: from /usr/local/lib/ruby/gems/2.7.0/gems/chronic-0.10.2/lib/chronic/parser.rb:247:in `block in tokens_to_span'
         4: from /usr/local/lib/ruby/gems/2.7.0/gems/chronic-0.10.2/lib/chronic/handler.rb:76:in `invoke'
         3: from /usr/local/lib/ruby/gems/2.7.0/gems/chronic-0.10.2/lib/chronic/handlers.rb:414:in `handle_r'
         2: from /usr/local/lib/ruby/gems/2.7.0/gems/chronic-0.10.2/lib/chronic/handlers.rb:526:in `get_anchor'
         1: from /usr/local/lib/ruby/gems/2.7.0/gems/chronic-0.10.2/lib/chronic/repeaters/repeater_time.rb:127:in `this'
/usr/local/lib/ruby/gems/2.7.0/gems/chronic-0.10.2/lib/chronic/repeaters/repeater_time.rb:111:in `next': Current time cannot be nil at this point (RuntimeError)
```

Unusual since we *output* a iso standard date in file, so not sure if it is getting confused somehow but it seemed a bit strange. Is it a bug? 

thanks,
Daryl.

**Comment by benprew** [comment]
Daryl,

Reckon tries to guess what the date column is, but is not doing a good job of guessing correctly.  For now, you can specify the column with the date in it, by using the --date-column option

ex:

`reckon --date-column 3 --contains-header -f csv92468-endFeb-prepped.csv -l ~/Dropbox/Apps/ledger/2020.ledger -o ./reckon_RBC_Visa_test-endFeb.ledger`

That should pick the correct column.  There's also a --money-column option if it doesn't pick the correct column for money.

I'll add additional phrasing to the warning about the date-column option.

Also, if you would be willing to share a few lines of your file (especially with the header), I'd like to use it as a regression test so that it correctly identifies the date column, at least in your case.

Thanks for using reckon and thanks for posting bugs, it helps us improve the gem for everyone.

**Comment by benprew** [comment]
@wakatara Just wanted to follow up on this, you're right, this is a big.  I fixed in the new version of the gem I released: 0.5.2.  Give it a try and let me know if you're still having problems.

Updating reckon should be as easy as `gem update --user reckon`. 

Worse case scenario, you can try removing and reinstalling reckon: `gem uninstall --user reckon`, followed by `gem install --user reckon`.

Once you're done, you can confirm reckon is the correct version by running `reckon --version`.

Thanks!

**Comment by wakatara** [comment]
Hey @benprew 

Thanks for spending the time fixing it for us out of North America types so fast! Have re-installed 0.52. Unfortunately, I tried testing with the previous file that threw the error and am still getting:

```
reckon --contains-header -f csv92468-endFeb-prepped.csv -l ~/Dropbox/Apps/ledger/2020_perso.ledger -o ./reckon_RBC_Visa_test-endFeb.ledger
What is the account name of this bank account in Ledger? |Assets:Bank:Checking| Assets:Visa
Using column 7 as the money column.  Use --money-colum to specify a different one.
W, [2020-03-09T11:26:33.481223 #17617]  WARN -- : Skipping row: 'Visa, 2020-02-20, GOJEK SINGAPORE 8.10 SGD @ .976500000000, -7.91, D' that doesn't have a valid date
W, [2020-03-09T11:26:33.482688 #17617]  WARN -- : Skipping row: 'Visa, 2020-02-20, GOJEK SINGAPORE 6.00 SGD @ .976600000000, -5.86, D' that doesn't have a valid date
W, [2020-03-09T11:26:33.484076 #17617]  WARN -- : Skipping row: 'Visa, 2020-02-20, GOJEK SINGAPORE 16.70 SGD @ .976600000000, -16.31, D' that doesn't have a valid date
W, [2020-03-09T11:26:33.485598 #17617]  WARN -- : Skipping row: 'Visa, 2020-02-20, GOJEK SINGAPORE 12.10 SGD @ .974300000000, -11.79, D' that doesn't have a valid date
W, [2020-03-09T11:26:33.486926 #17617]  WARN -- : Sk
```

A sample of the csv file is here: 
```
Account,Date,Description,CAD$,Trxn type
Visa,2020-02-20,GOJEK SINGAPORE 8.10 SGD @ .976500000000,-7.91,D
Visa,2020-02-20,GOJEK SINGAPORE 6.00 SGD @ .976600000000,-5.86,D
Visa,2020-02-20,GOJEK SINGAPORE 16.70 SGD @ .976600000000,-16.31,D
Visa,2020-02-20,GOJEK SINGAPORE 12.10 SGD @ .974300000000,-11.79,D
Visa,2020-02-23,COTTON BUREAU HTTPSCOTTONBUPA 35.40 USD @ 1.359800000000,-48.14,D
Visa,2020-02-23,SISTIC.COM PTE LTD SINGAPORE 408.00 SGD @ .918600000000,374.82,C
```

note also when it says the money column is trying to use is column 7 there are only 5 columns so I think the FX info in the 3rd one might be throwing it off somehow (I assume if I just bracket that with " " it'll correct it most likely though. 

Hope that helps and again, thanks for spending the time squashing bugs and making such a useful gem.

**Comment by benprew** [comment]
Thanks for following up @wakatara, I'll add a test for this and I agree that it saying column 7 is questionable.

I'll reopen this issue.
