### ISSUE TITLE
[Feature Request] Note flag --add-notes in CLI to allow additional notes for each ledger entry

### ISSUE THREAD

**Issue by wakatara** [cantino/reckon#86]
Would just like to tell you how much work you've saved me on importing bank statements (with 3 banks in various countries.). Love the gem.

One thing that would be helpful for me is that quite often the imported bank statements have nonsensical strings attached to them in the description fields or will be for someplace I don't go very often. It would be great if we could pass a flag that allows us to enter a note (or simply hit return to bypass that) and that got introduced into that entry. 
eg.
```
Misc DR-Debit Card AJI-ICHI SINGAPORE 28 FEB 4934 9430378
```

Could not remember for the life of me what this charge was until I googled and found out it was a random dinner near the Observatory when I went to do some star gazing (and was underwhelming). Being able to add in a note to the effect of `S Dinner @ Observatory outing` for entries when I puzzle them out would be amazing and super helpful when going back and looking at things.

(I checked this time and it doesn't "appear" that that feature is available, but it woudl be very awesome to have added in if possible. Especially for reconciliation purposes.)

thanks!

**Comment by wakatara** [comment]
I am working on a golang thing right now, but will swing back around after this and another code thingy to take a peek at how tricky that would be to add into the gem. Did want to let you know I mentioned Reckon heavily in a blog post on [managing your finances easily](https://daryl.wakatara.com/tracking-your-finances-with-reckon-and-ledger/). Again, thanks for all the awesome work on Reckon, I really do believe I would not have continued using ledger without it. 
have a great weekend.

**Comment by benprew** [comment]
Hey @wakatara , I know it's been a while, but I have an implementation for adding descriptions to transactions (this is something that I wanted to do as well).

It's currently in a branch, but I've attached the built version that you can install and test.  I've got some more testing to do, but should get it merged into mainline soon.

[reckon-0.5.4.1.zip](https://github.com/cantino/reckon/files/5013284/reckon-0.5.4.1.zip)

**Comment by wakatara** [comment]
Hey there!

That is awesome. Grabbed the zip and it is good timing as I have to do my July finance checks this week, so will have a chance to test on live data (and lots to comment about since did a lot of unusual finance things this past month - capitalized company, stock purchases etc.). Also, just breaking in a new linux laptop and seeing about moving off the Macbook Air, so will check on both platforms (Manjaro i3 vs OSX)

Should be able to get you some answers in next 3 days or so. That work?

(and as always, thanks for the work on this. I was bragging to some folks last week about ML was solving my financial accounting issues since they had spent two whole days on their business accounting. :stuck_out_tongue_closed_eyes: ).

**Comment by wakatara** [comment]
@benprew 

I ran this through a pretty complex set of accounts across two different countries to get my monthly personal figures and it works great. Manjaro linux, 20.0.3 using i3 on the 5.7.9-1 kernel. Works great. Did you make some tweaks to the ML algo as well? 

I'd just suggest one tweak to the functionality if it's not too cheeky as I imagine a lot of people would want it: 

I'd actually have two options available which do the same thing slightly differently, rather than jus "(d)escribe".

The first would be (r) replace description which over-writes the bank string in the original position like you have the feature now and a (n) add note which adds a commented line *under* the original bank string with a `; Your note here` which acts as an annotation on the original record. 

I know for me, I probably need to have the original bank record in for tracinf/audit purposes for the auditor and accountant and the notation would just keep me from going insane on most of my records when I have way too many computer generated codes in that orgiinal bank string. 

But, the thing is definitely working nicely. Great work!

ciao! (and thanks for working on this!)

**Comment by benprew** [comment]
Great, glad it's working so well!  As far as the ML algo goes, I didn't make any changes to the algorithm itself, but I did make some small changes to how the terms in the transaction are tokenized, which could give better suggestions.

I like your idea of adding a note instead of renaming the transaction, I agree that for tracing purposes having the original transaction is important (and necessary for auditing cases).  I'll make some changes and send you an updated version to try out.

**Comment by benprew** [comment]
Ok, I added a [n]ote option in addition to description and pushed a new version of reckon (0.6.0), give it a try and let me know what you think.

**Comment by wakatara** [comment]
Cool! This came the precise day *after* I'd already done my financial stuff for the month, so might need to wait till next month for a more rigorous test, but will give it a go on last month's data soon as I get a chance (cause a lot of it had to be annotated due to a lot of strange bank codes/wording on what the things actually were. Lemme update the gem and check it out. Be back soon.

**Comment by Daryl-DH** [comment]
Works the charm. Liking it. You can definitely close this ticket, I think.
