### ISSUE TITLE
order of transactions

### ISSUE THREAD

**Issue by hoclun-rigsep** [cantino/reckon#88]
Does reckon care about the order of the transactions? I was debugging my monthly script and in the function that preprocesses the csv, the difference between success and failure was a `|tac`:

    sed '1d' "$1" | sed 's/[#*]//' | tac > "$tmpfile"  # with the |tac i get the following error

    Traceback (most recent call last):
        8: from /usr/local/bin/reckon:24:in `<main>'
        7: from /usr/local/bin/reckon:24:in `load'
        6: from /var/lib/gems/2.5.0/gems/reckon-0.5.2/bin/reckon:19:in `<top (required)>'
        5: from /var/lib/gems/2.5.0/gems/reckon-0.5.2/lib/reckon/app.rb:95:in `walk_backwards'
        4: from /var/lib/gems/2.5.0/gems/reckon-0.5.2/lib/reckon/app.rb:158:in `each_row_backwards'
        3: from /var/lib/gems/2.5.0/gems/reckon-0.5.2/lib/reckon/app.rb:158:in `each'
        2: from /var/lib/gems/2.5.0/gems/reckon-0.5.2/lib/reckon/app.rb:168:in `block in each_row_backwards'
        1: from /var/lib/gems/2.5.0/gems/reckon-0.5.2/lib/reckon/csv_parser.rb:56:in `description_for'
    /var/lib/gems/2.5.0/gems/reckon-0.5.2/lib/reckon/csv_parser.rb:56:in `reject': undefined method    `empty?' for nil:NilClass (NoMethodError)

This is another issue that I don't believe I was experiencing in an earlier version of reckon.

**Comment by benprew** [comment]
Interesting, what does the first row of the file look like?  It looks like the csv_parser uses the first column length to determine the # of rows in the file, but if one of those rows has a date but not a description, it would fail like this.

If you can provide some sample transactions that would be great, if not, I can make the code more defensive.

Thanks for reporting this issue and thanks for using reckon.

**Comment by hoclun-rigsep** [comment]
Yeah I definitely was hastier than I ought to be when filing this. I would hate to waste your time; I suggest letting me get back to you with more.

**Comment by benprew** [comment]
No worries, it's definitely a bug and I'd rather have the bug report than not :)

**Comment by hoclun-rigsep** [comment]
I can't reproduce this; there must have been something else going on. Sorry!

**Comment by benprew** [comment]
Ok, I pushed some changes to make `description_for` a little more defensive, thanks for reporting this.
