### ISSUE TITLE
Migrate CI system from travis-ci.org

### ISSUE THREAD

**Issue by benprew** [cantino/reckon#93]
Hey @cantino, travis-ci is [updating their CI plans](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing), and removing the free unlimited open source plan.  Instead, they'll have a [free plan](https://docs.travis-ci.com/user/billing-overview/) that has limited credits which are not replenished.

> Free Plan #
>
> A ‘Free’ Plan, assigned automatically to every new sign up, is a Usage based plan without limits on users and comes with a trial pool of credits to be used. Once these credits are used they are not replenished. Request OSS Credits allowance or please consider one of our available plans.

Github Actions offers [free CI for public repos](https://github.blog/2019-08-08-github-actions-now-supports-ci-cd/), so I was thinking we should migrate reckon to use that.

I think I have permissions to setup github actions, but wanted to get your thoughts before setting that up.

Thanks

**Comment by benprew** [comment]
Blog post on someone else who migrated from Travis to Github Actions: 
- https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works

**Comment by cantino** [comment]
I'm fine if you want to migrate the project— you're very much the maintainer at this point (and doing a great job!). Is there anything I need to do to make sure you can move forward?
