### ISSUE TITLE
read from stdin

### ISSUE THREAD

**Issue by raboof** [cantino/reckon#95]
reckon is really nice, I had my banks' CSV export converted to ledger format in no time.

it would make my workflow a bit simpler if reckon supported passing in `-f -` to read the CSV from stdin.

**Comment by benprew** [comment]
I'm glad you're liking reckon.  :)  I think this would be a pretty easy change, I'll look into it and see what it would take to add support for this.

**Comment by benprew** [comment]
This should be available now in the v0.6.1 version of reckon.

**Comment by raboof** [comment]
it seems #98 wasn't merged yet?

**Comment by benprew** [comment]
Ahh, good catch, that PR is merged and 0.6.2 has been released.

Thanks!

**Comment by raboof** [comment]
Tested, noticed https://github.com/cantino/reckon/pull/98/files#r563527597 in the output that should probably be removed?
