### ISSUE TITLE
spaces in tokens

### ISSUE THREAD

**Issue by raboof** [cantino/reckon#97]
right now if you add for example 'ING BE >Brussels' as a token to be assigned to a certain account, it seems it will also match other lines that contain for example just 'ING'. I think it would be useful to be more specific.

**Comment by raboof** [comment]
as a workaround `/ING BE >Brussels/i` does work

**Comment by benprew** [comment]
Hi @raboof, thanks for using reckon.  I think what's happening is the account tokes file is used for training the tf-idf matcher, so it tokenizes ING BE >Brussels into tokens ['ING', 'BE', 'Brussels'].  Regexes do not get tokenized, so if you want an exact or substring match using a regex works.

I could change reckon to use the string as a substring match only, but it would complicate the code by adding a 3rd path for matching: regex, tf-idf and substring tokens.  Additionally it would break the existing behaviour (if anyone is relying on it)

I like the solution of using a regex to do substring matching, I'll update the documentation to clarify how account tokens work and provide some examples.

Thanks

**Comment by raboof** [comment]
> Hi @raboof, thanks for using reckon.

Thanks for the quick responses!

> I could change reckon to use the string as a substring match only, but it would complicate the code by adding a 3rd path for matching: regex, tf-idf and substring tokens.

I guess you could convert the strings to regex'es

> I like the solution of using a regex to do substring matching, I'll update the documentation to clarify how account tokens work and provide some examples.

Just adding some examples clarifying the file format and showing how to use regexes to achieve substring matching would be a fine solution as well though :D

**Comment by benprew** [comment]
@raboof I added a section on Account Tokens in the README that explains this a little more, let me know what you think.

**Comment by raboof** [comment]
Looks good, thanks!
